
require 'diaspora-federation/entities/entity'

require 'diaspora-federation/entities/account_deletion'
require 'diaspora-federation/entities/comment'
#require 'diaspora-federation/entities/conversation'
require 'diaspora-federation/entities/like'
require 'diaspora-federation/entities/location'
require 'diaspora-federation/entities/message'
require 'diaspora-federation/entities/participation'
#require 'diaspora-federation/entities/person'
require 'diaspora-federation/entities/photo'
require 'diaspora-federation/entities/post'
require 'diaspora-federation/entities/profile'
require 'diaspora-federation/entities/relayable_retraction'
require 'diaspora-federation/entities/request'
require 'diaspora-federation/entities/reshare'
require 'diaspora-federation/entities/retraction'
require 'diaspora-federation/entities/signed_retraction'
#require 'diaspora-federation/entities/status_message'
