# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

# spec code coverage
require 'coveralls'
Coveralls.wear!

require 'diaspora_federation'
require 'ostruct'
require 'fabrication'

require 'fabricators'

require 'diaspora-federation/entities/shared_entity_specs'
require 'diaspora-federation/salmon/shared_slap_specs'
require 'diaspora-federation/validators/shared_validator_specs'

include DiasporaFederation

module Entities
  class TestEntity < Entity
    define_props do
      property :test
    end
  end

  class OtherEntity < Entity
    define_props do
      property :asdf
    end
  end

  class TestNestedEntity < Entity
    define_props do
      property :asdf
      entity :test, TestEntity
      entity :multi, [OtherEntity]
    end
  end
end

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
